# Generated by Django 4.2 on 2023-05-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0)),
                ('benefits', models.CharField(blank=True, max_length=255, null=True)),
                ('face_type', models.CharField(blank=True, choices=[('Dry Skin', 'Dry Skin'), ('Oily Skin', 'Oily Skin')], max_length=255, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_products', models.CharField(blank=True, choices=[('Loreal', 'Loreal'), ('Pearls', 'Pearls'), ('Nivia', 'Nivia')], max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.services')),
            ],
        ),
    ]
