# Generated by Django 4.2 on 2023-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
