# Generated by Django 4.2 on 2023-05-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0005_alter_atomcategory_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomcategory',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
