# Generated by Django 4.2 on 2023-05-02 08:35

from django.db import migrations, models
import sc.models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0006_alter_atomcategory_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sc.models.get_sub_image_path),
        ),
    ]
