# Generated by Django 4.2 on 2023-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0007_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
